services:
  - type: web
    name: FaceDetectatron
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    timeout: 400
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: MODEL_NAME
        value: Facenet
      - key: DB_DIM
        value: "128"
      - key: INDEX_NAME
        value: breadmaker
